sonar.sources=contracts,scripts
sonar.tests=test,test-js
sonar.exclusions=node_modules/**,artifacts/**,cache/**
sonar.coverage.exclusions=contracts/**,scripts/deploy.js
sonar.javascript.lcov.reportPaths=coverage-js/lcov.info,coverage/lcov.info
