fullnameOverride: ""

global:
  partOf: blockchain-secrets-vault

postgres:
  image:
    repository: postgres
    tag: 16-alpine
    pullPolicy: IfNotPresent
  service:
    port: 5432
  auth:
    database: secretsvault
    username: secretsvault
    password: ""
  persistence:
    size: 4Gi
    storageClassName: ""
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

redis:
  image:
    repository: redis
    tag: 7.4-alpine
    pullPolicy: IfNotPresent
  replicas: 1
  service:
    port: 6379
  resources:
    requests:
      cpu: 50m
      ephemeral-storage: 64Mi
      memory: 64Mi
    limits:
      cpu: 250m
      ephemeral-storage: 128Mi
      memory: 256Mi

blockchainNode:
  image:
    repository: ghcr.io/igorsatsyuk/blockchain-secrets-vault/blockchain-node
    tag: 0.1.0
    pullPolicy: IfNotPresent
  replicas: 1
  service:
    port: 8545
  resources:
    requests:
      cpu: 100m
      ephemeral-storage: 256Mi
      memory: 256Mi
    limits:
      cpu: 500m
      ephemeral-storage: 512Mi
      memory: 512Mi

secretsApi:
  image:
    repository: ghcr.io/igorsatsyuk/blockchain-secrets-vault/secrets-api
    tag: 0.1.0
    pullPolicy: IfNotPresent
  replicas: 1
  service:
    port: 8080
  config:
    authUsername: admin
    authIssuer: blockchain-secrets-vault
    authTokenTtl: PT1H
    blockchainAclRpcUrl: ""
    blockchainAclGasPrice: "20000000000"
    blockchainAclGasLimit: "300000"
    blockchainAclChainId: "31337"
  secrets:
    authPassword: ""
    authJwtSecret: ""
    blockchainAclContractAddress: ""
    blockchainAclPrivateKey: ""
  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 10001
    runAsGroup: 10001
  resources:
    requests:
      cpu: 200m
      ephemeral-storage: 256Mi
      memory: 512Mi
    limits:
      cpu: 1000m
      ephemeral-storage: 512Mi
      memory: 1024Mi

frontend:
  image:
    repository: ghcr.io/igorsatsyuk/blockchain-secrets-vault/frontend
    tag: 0.1.0
    pullPolicy: IfNotPresent
  replicas: 1
  service:
    port: 80
    targetPort: 8080
  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
  resources:
    requests:
      cpu: 50m
      ephemeral-storage: 64Mi
      memory: 64Mi
    limits:
      cpu: 250m
      ephemeral-storage: 128Mi
      memory: 128Mi

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: ""
      apiPath: /api
      frontendPath: /
