apiVersion: v1
kind: ConfigMap
metadata:
  name: secrets-api-config
data:
  SECRETS_AUTH_USERNAME: admin
  SECRETS_AUTH_ISSUER: blockchain-secrets-vault
  SECRETS_AUTH_TOKEN_TTL: PT1H
  BLOCKCHAIN_ACL_RPC_URL: http://blockchain-node:8545
  BLOCKCHAIN_ACL_GAS_PRICE: "20000000000"
  BLOCKCHAIN_ACL_GAS_LIMIT: "300000"
  BLOCKCHAIN_ACL_CHAIN_ID: "31337"
---
apiVersion: v1
kind: Secret
metadata:
  name: secrets-api-secrets
type: Opaque
stringData:
  SECRETS_AUTH_PASSWORD: change-me-admin-password
  SECRETS_AUTH_JWT_SECRET: change-me-jwt-secret-at-least-32-bytes
  BLOCKCHAIN_ACL_CONTRACT_ADDRESS: ""
  BLOCKCHAIN_ACL_PRIVATE_KEY: ""
---
apiVersion: v1
kind: Service
metadata:
  name: secrets-api
spec:
  selector:
    app.kubernetes.io/name: secrets-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: secrets-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: secrets-api
    spec:
      containers:
        - name: secrets-api
          image: ghcr.io/igorsatsyuk/blockchain-secrets-vault/secrets-api:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: secrets-api-config
            - secretRef:
                name: secrets-api-secrets
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
